/**
 * ============================================================================
 * DEMO RETRIEVAL CONTENT — NOT AUTHORED CURRICULUM
 * ============================================================================
 *
 * Spiral Review draws only from the lesson's own subject, and the selector takes
 * at most one item per skill. A course therefore needs items across SEVERAL
 * distinct standards before it can offer the five to seven items the blueprint
 * asks for — one standard with three items still yields one question.
 *
 * These cover the courses the named demo students are actually enrolled in, so
 * a reviewer clicking any of them meets a real Spiral Review rather than an
 * empty one. Every item sits on a lesson that claims its standard as PRIMARY
 * coverage, and every wrong choice names the error family it reveals. No
 * curriculum author has reviewed or adopted them, and every surface that renders
 * one says so (ADR 0005).
 *
 * Where a course's standards rotate through a short list — Human Geography's
 * framework objectives, Physics's opening units — the bank is correspondingly
 * short. That is the curriculum's own shape, not a gap in the bank, and the
 * review a student is offered is honestly smaller.
 */
import { item, type DemoItem } from "./demo-item";

// ---------------------------------------------------------------------------
// Mathematics
// ---------------------------------------------------------------------------

/** Mathematics 7 · units 1-2 · rational-number operations and proportionality */
const MATH_07: DemoItem[] = [
  item("I-M7NS1c-01", "MATH-07-L003", "7.NS.1.c", "spiral_review",
    "Which expression is equivalent to 5 − (−3)?",
    [["5 + 3", null],
     ["5 − 3", "sign"],
     ["−5 + 3", "sign"],
     ["−(5 + 3)", "sign"]], 0,
    "Subtracting a number is adding its additive inverse. The inverse of −3 is +3, so 5 − (−3) = 5 + 3 = 8."),
  item("I-M7NS2b-01", "MATH-07-L006", "7.NS.2.b", "spiral_review",
    "What is (−12) ÷ 4?",
    [["−3", null],
     ["3", "sign"],
     ["−8", "inverse-operation"],
     ["−48", "inverse-operation"]], 0,
    "A negative divided by a positive is negative, and 12 ÷ 4 = 3, so the quotient is −3."),
  item("I-M7NS3-01", "MATH-07-L009", "7.NS.3", "spiral_review",
    "At 6 a.m. the temperature was −4 °C. By noon it had risen 11 degrees. What was the temperature at noon?",
    [["7 °C", null],
     ["−15 °C", "sign"],
     ["15 °C", "sign"],
     ["−7 °C", "sign"]], 0,
    "Rising 11 degrees from −4 means −4 + 11 = 7. A rise adds; only the starting value is negative."),
  item("I-M7RP1-01", "MATH-07-L016", "7.RP.1", "spiral_review",
    "A walker covers 1/2 mile in 1/4 hour. What is the speed in miles per hour?",
    [["2 miles per hour", null],
     ["1/8 mile per hour", "inverse-operation"],
     ["1/2 mile per hour", "unit-and-scale"],
     ["4 miles per hour", "calculation"]], 0,
    "'Per hour' means divide by the hours: (1/2) ÷ (1/4) = (1/2) × 4 = 2. Multiplying instead of dividing gives 1/8, which answers nothing that was asked."),
  item("I-M7RP2a-01", "MATH-07-L017", "7.RP.2.a", "spiral_review",
    "A table pairs 2 with 5, 4 with 10, and 6 with 16. Is the relationship proportional?",
    [["No — 6 and 16 do not give the same ratio as the other pairs", null],
     ["Yes — each input increases by 2", "proportional-vs-additive"],
     ["Yes — every output is larger than its input", "proportional-vs-additive"],
     ["There is not enough information to decide", "representation"]], 0,
    "Proportional means every pair has the SAME ratio. 5/2 and 10/4 are both 2.5; 16/6 is not. A constant step between inputs is an additive pattern, not a proportional one."),
  item("I-M7RP2b-01", "MATH-07-L018", "7.RP.2.b", "spiral_review",
    "A graph of cost against pounds passes through the origin and through (3, 7.50). What is the constant of proportionality?",
    [["2.50 dollars per pound", null],
     ["0.40 pounds per dollar", "inverse-operation"],
     ["7.50 dollars per pound", "unit-and-scale"],
     ["4.50 dollars per pound", "calculation"]], 0,
    "The constant of proportionality is the value of y when x is 1: 7.50 ÷ 3 = 2.50 dollars per pound."),
];

/** Math 3 · units 1-2 · polynomial structure and rational equations */
const MATH_3: DemoItem[] = [
  item("I-M3NCN9-01", "MATH-3-L002", "N-CN.9", "spiral_review",
    "How many roots does a fourth-degree polynomial have, counting multiplicity and allowing complex numbers?",
    [["Exactly four", null],
     ["At most four, and possibly none", "theorem-misapplied"],
     ["Four, but only if it factors over the real numbers", "theorem-misapplied"],
     ["It depends on the leading coefficient", "theorem-misapplied"]], 0,
    "The Fundamental Theorem of Algebra: a degree-n polynomial has exactly n complex roots when multiplicity is counted. Some of them may not be real."),
  item("I-M3APR1-01", "MATH-3-L003", "A-APR.1", "spiral_review",
    "Which operation can take two polynomials and produce something that is NOT a polynomial?",
    [["Division", null],
     ["Addition", "theorem-misapplied"],
     ["Subtraction", "theorem-misapplied"],
     ["Multiplication", "theorem-misapplied"]], 0,
    "Polynomials are closed under addition, subtraction, and multiplication, like the integers. Division is the one that can leave the system, which is why rational expressions exist."),
  item("I-M3APR2-01", "MATH-3-L004", "A-APR.2", "spiral_review",
    "For p(x) = x³ − 4x + 1, what does p(2) tell you?",
    [["The remainder when p(x) is divided by (x − 2)", null],
     ["The remainder when p(x) is divided by (x + 2)", "sign"],
     ["The value of the leading coefficient", "theorem-misapplied"],
     ["Whether p(x) has any complex roots", "theorem-misapplied"]], 0,
    "The Remainder Theorem: p(a) is the remainder on division by (x − a). Here p(2) = 1, so (x − 2) is not a factor."),
  item("I-M3APR3-01", "MATH-3-L005", "A-APR.3", "spiral_review",
    "p(x) = (x + 1)(x − 3)². Where does the graph of p cross or touch the x-axis?",
    [["Crosses at −1, touches at 3", null],
     ["Crosses at 1, touches at −3", "sign"],
     ["Crosses at both −1 and 3", "theorem-misapplied"],
     ["Touches at both −1 and 3", "theorem-misapplied"]], 0,
    "A factor raised to an odd power crosses the axis; an even power touches and turns. (x − 3) is squared, so the graph meets the axis at 3 without crossing."),
  item("I-M3APR6-01", "MATH-3-L008", "A-APR.6", "spiral_review",
    "Rewrite (x² + 3x + 5) ÷ (x + 1) in the form q(x) + r/(x + 1).",
    [["x + 2 + 3/(x + 1)", null],
     ["x + 2", "theorem-misapplied"],
     ["x + 3 + 5/(x + 1)", "calculation"],
     ["x + 4 − 1/(x + 1)", "calculation"]], 0,
    "Dividing gives quotient x + 2 with remainder 3. Dropping the remainder turns the expression into a different function."),
  item("I-M3ACED1-01", "MATH-3-L018", "A-CED.1", "spiral_review",
    "A tank drains so that 300/(t + 2) litres remain after t minutes. Which equation finds when 50 litres remain?",
    [["300/(t + 2) = 50", null],
     ["300 = 50(t + 2) + 300", "variable-interpretation"],
     ["50/(t + 2) = 300", "inverse-operation"],
     ["300(t + 2) = 50", "inverse-operation"]], 0,
    "Set the expression for what remains equal to the amount being asked about. The others rearrange the relationship into a different claim."),
];

/** Statistics · units 1-2 · distributions and bivariate data */
const MATH_STATS: DemoItem[] = [
  item("I-STID1-01", "MATH-STATS-L001", "S-ID.1", "spiral_review",
    "Which display shows the SHAPE of a distribution most directly?",
    [["A histogram", null],
     ["A box plot", "representation"],
     ["A two-way table", "representation"],
     ["A bar chart of categories", "representation"]], 0,
    "A histogram shows how the values pile up across the range. A box plot summarises five numbers and can hide a gap or a second peak entirely."),
  item("I-STID2-01", "MATH-STATS-L002", "S-ID.2", "spiral_review",
    "Two classes have the same mean score. Class A's standard deviation is 4; Class B's is 12. What does that say?",
    [["Scores in Class B are more spread out around the same centre", null],
     ["Class B scored higher overall", "representation"],
     ["Class B has more students", "representation"],
     ["Class A has more outliers", "representation"]], 0,
    "Standard deviation measures spread, not level and not group size. Same centre, wider scatter."),
  item("I-STID3-01", "MATH-STATS-L003", "S-ID.3", "spiral_review",
    "One value in a small data set is replaced by a number ten times larger. Which summary changes least?",
    [["The median", null],
     ["The mean", "representation"],
     ["The range", "representation"],
     ["The standard deviation", "representation"]], 0,
    "The median depends on position, not magnitude, so a single extreme value barely moves it. The mean, the range, and the standard deviation all use the value itself."),
  item("I-STID6-01", "MATH-STATS-L006", "S-ID.6", "spiral_review",
    "A residual plot for a linear fit shows a clear U shape. What does that indicate?",
    [["A linear model is the wrong form for this relationship", null],
     ["The correlation is negative", "representation"],
     ["There is one outlier in the data", "representation"],
     ["The fit is good, because the residuals are small", "no-verification"]], 0,
    "Residuals should scatter without pattern. A curve in the residuals says the model missed structure that is really there."),
  item("I-STID7-01", "MATH-STATS-L007", "S-ID.7", "spiral_review",
    "A line predicting monthly cost from hours used has slope 0.40 and intercept 15. What does the slope mean?",
    [["Each additional hour adds $0.40 to the cost", null],
     ["The cost when no hours are used is $0.40", "representation"],
     ["The total monthly cost is $0.40", "representation"],
     ["It takes 0.40 hours to reach $15", "inverse-operation"]], 0,
    "Slope is the change in the response per one unit of the predictor. The intercept, 15, is the cost at zero hours."),
  item("I-STID9-01", "MATH-STATS-L009", "S-ID.9", "spiral_review",
    "Ice-cream sales and drowning incidents rise together across the year. What follows?",
    [["Something else, such as hot weather, may be driving both", null],
     ["Ice-cream sales cause drownings", "correlation-as-cause"],
     ["Drownings cause ice-cream sales", "correlation-as-cause"],
     ["The correlation must be a calculation error", "no-verification"]], 0,
    "A strong correlation says two things move together. Only a controlled comparison, or a stated mechanism, can say one causes the other."),
];

// ---------------------------------------------------------------------------
// Science
// ---------------------------------------------------------------------------

/** Integrated Science 7 · units 1-2 · matter, atomic models, and reactions */
const SCI_07: DemoItem[] = [
  item("I-S7PS11-01", "SCI-07-L001", "MS-PS1-1", "spiral_review",
    "A model shows one carbon atom bonded to two oxygen atoms. What does the model represent?",
    [["A molecule of a compound", null],
     ["A mixture of carbon and oxygen", "model-omits-component"],
     ["Three separate elements", "model-omits-component"],
     ["An atom of a new element", "model-omits-component"]], 0,
    "Atoms bonded together form a molecule. A mixture keeps its substances separate and separable; a compound has them chemically joined."),
  item("I-S7PS12-01", "SCI-07-L002", "MS-PS1-2", "spiral_review",
    "Which observation is the strongest evidence that a CHEMICAL reaction occurred?",
    [["A gas formed and the substance no longer dissolves as it did", null],
     ["The mixture got colder when stirred", "mechanism-missing"],
     ["The solid broke into smaller pieces", "mechanism-missing"],
     ["The liquid took the shape of a new container", "mechanism-missing"]], 0,
    "A chemical reaction produces substances with different properties. Breaking, pouring, and changing shape are physical changes — the substance is still the same substance."),
  item("I-S7PS13-01", "SCI-07-L003", "MS-PS1-3", "spiral_review",
    "Which is a synthetic material made from a natural resource?",
    [["Nylon, made from petroleum", null],
     ["Cotton, picked from a plant", "mechanism-missing"],
     ["Granite, quarried from rock", "mechanism-missing"],
     ["Spring water, drawn from the ground", "mechanism-missing"]], 0,
    "Synthetic means built by a chemical process from something else. Cotton, granite, and water are used essentially as found."),
  item("I-S7PS14-01", "SCI-07-L016", "MS-PS1-4", "spiral_review",
    "A sealed syringe of air is warmed. What happens at the particle scale?",
    [["The particles move faster and push out harder", null],
     ["The particles themselves get bigger", "model-omits-component"],
     ["New particles are created by the heat", "conservation-ignored"],
     ["The particles stop colliding with the walls", "model-omits-component"]], 0,
    "Adding thermal energy increases particle motion. The particles do not change size, and none are created — the same particles are simply moving faster."),
  item("I-S7PS15-01", "SCI-07-L017", "MS-PS1-5", "spiral_review",
    "12 g of a solid reacts completely with 8 g of a liquid in a sealed flask. What is the mass of the products?",
    [["20 g", null],
     ["Less than 20 g, because gas escaped", "conservation-ignored"],
     ["12 g, because the solid is what reacted", "conservation-ignored"],
     ["It cannot be known without the formula", "no-verification"]], 0,
    "Atoms are rearranged, never destroyed, so total mass is conserved. Sealed means nothing left, so 12 + 8 = 20 g."),
  item("I-S7PS16-01", "SCI-07-L018", "MS-PS1-6", "spiral_review",
    "You are designing a device that must get COLD when two chemicals mix. Which reaction do you need?",
    [["One that absorbs thermal energy from its surroundings", null],
     ["One that releases thermal energy to its surroundings", "mechanism-missing"],
     ["One that produces the most gas", "mechanism-missing"],
     ["One that happens fastest", "mechanism-missing"]], 0,
    "A cold pack works because the reaction takes energy IN. Speed and gas volume are different design criteria."),
];

/** Integrated Science 8 · units 1-2 · Earth-space systems, forces and motion */
const SCI_08: DemoItem[] = [
  item("I-S8ESS11-01", "SCI-08-L001", "MS-ESS1-1", "spiral_review",
    "Why does the Moon show phases?",
    [["We see different fractions of its lit half as it orbits Earth", null],
     ["Earth's shadow covers part of it each night", "model-omits-component"],
     ["The Moon produces less light at some times", "model-omits-component"],
     ["Clouds block part of it", "model-omits-component"]], 0,
    "Half the Moon is always lit. The phase is how much of that lit half faces us. Earth's shadow falling on the Moon is a lunar eclipse — a different and much rarer event."),
  item("I-S8ESS12-01", "SCI-08-L002", "MS-ESS1-2", "spiral_review",
    "What keeps the planets in orbit around the Sun?",
    [["Gravity, acting between the Sun and each planet", null],
     ["The Sun's magnetic field", "mechanism-missing"],
     ["The push of the solar wind", "mechanism-missing"],
     ["Nothing — objects in space keep moving on their own", "mechanism-missing"]], 0,
    "Gravity supplies the inward force that bends a planet's straight-line motion into an orbit. Without it a planet would travel off in a straight line."),
  item("I-S8ESS13-01", "SCI-08-L003", "MS-ESS1-3", "spiral_review",
    "Jupiter's diameter is about 11 times Earth's. What does that let you say?",
    [["Jupiter's volume is far more than 11 times Earth's", null],
     ["Jupiter's volume is exactly 11 times Earth's", "scale-confusion"],
     ["Jupiter has 11 times Earth's mass", "scale-confusion"],
     ["Jupiter is 11 times farther from the Sun", "scale-confusion"]], 0,
    "Volume scales with the cube of the diameter, so roughly 11³ ≈ 1,300 times. Diameter, mass, and distance are three separate measurements."),
  item("I-S8ESS14-01", "SCI-08-L004", "MS-ESS1-4", "spiral_review",
    "In undisturbed rock layers, which layer is oldest?",
    [["The bottom one", null],
     ["The top one", "no-temporal-relationship"],
     ["The thickest one", "no-temporal-relationship"],
     ["The one with the most fossils", "no-temporal-relationship"]], 0,
    "Layers are deposited from the bottom up, so the deepest undisturbed layer was laid down first. Thickness and fossil content say nothing about order."),
  item("I-S8PS21-01", "SCI-08-L016", "MS-PS2-1", "spiral_review",
    "A book rests on a table, and the table pushes up on the book. What is the paired force?",
    [["The book pushes down on the table", null],
     ["Earth pulls down on the book", "force-pair-confusion"],
     ["The table pushes down on the floor", "force-pair-confusion"],
     ["Air pushes down on the book", "force-pair-confusion"]], 0,
    "A Newton's-third-law pair acts between the SAME two objects, in opposite directions. Table on book pairs with book on table; Earth's pull is a different interaction."),
  item("I-S8PS22-01", "SCI-08-L017", "MS-PS2-2", "spiral_review",
    "Two carts are pushed with the same force. Cart A has twice the mass of cart B. What happens?",
    [["Cart B speeds up twice as fast as cart A", null],
     ["Both speed up at the same rate", "mechanism-missing"],
     ["Cart A speeds up twice as fast", "inverse-operation"],
     ["Neither moves without a bigger push", "mechanism-missing"]], 0,
    "The same force acting on more mass produces less change in motion. Half the mass, twice the acceleration."),
];

/** Biology · units 1-2 · cells, and matter and energy in organisms */
const SCI_BIO: DemoItem[] = [
  item("I-BIOLS11-01", "SCI-BIO-L001", "HS-LS1-1", "spiral_review",
    "What is the relationship between DNA and proteins in a cell?",
    [["DNA carries the instructions that specify each protein's structure", null],
     ["DNA is built out of proteins", "model-omits-component"],
     ["Proteins copy themselves directly from other proteins", "mechanism-missing"],
     ["DNA and proteins do the same job in different parts of the cell", "model-omits-component"]], 0,
    "Genes are sections of DNA that specify a protein's sequence, and that sequence determines the structure which lets the protein do its job."),
  item("I-BIOLS12-01", "SCI-BIO-L002", "HS-LS1-2", "spiral_review",
    "Put these in order from smallest to largest level of organization.",
    [["Cell, tissue, organ, organ system", null],
     ["Cell, organ, tissue, organ system", "scale-confusion"],
     ["Tissue, cell, organ system, organ", "scale-confusion"],
     ["Organ, organ system, tissue, cell", "scale-confusion"]], 0,
    "Cells of one kind form a tissue, tissues form an organ, and organs working together form a system. Each level does something the level below cannot do alone."),
  item("I-BIOLS13-01", "SCI-BIO-L003", "HS-LS1-3", "spiral_review",
    "Sweating when body temperature rises is an example of what?",
    [["Negative feedback, which returns a condition toward its set point", null],
     ["Positive feedback, which pushes a condition further from its set point", "mechanism-missing"],
     ["A one-off response with no set point involved", "mechanism-missing"],
     ["A change in the set point itself", "mechanism-missing"]], 0,
    "Negative feedback opposes the change that triggered it. Sweating cools, which counteracts the rise — that is what keeps the internal condition stable."),
  item("I-BIOLS15-01", "SCI-BIO-L016", "HS-LS1-5", "spiral_review",
    "In photosynthesis, where does the carbon in a plant's sugar come from?",
    [["Carbon dioxide taken from the air", null],
     ["The soil the plant grows in", "mechanism-missing"],
     ["The water taken up by the roots", "model-omits-component"],
     ["Sunlight absorbed by the leaves", "model-omits-component"]], 0,
    "Light supplies the energy; CO₂ supplies the carbon. Most of a plant's dry mass comes from air, which is the result students find hardest to believe."),
  item("I-BIOLS16-01", "SCI-BIO-L017", "HS-LS1-6", "spiral_review",
    "An organism builds proteins and fats. Where do the carbon atoms in those molecules come from?",
    [["Sugar molecules already made or taken in", null],
     ["They are created by the cell as needed", "conservation-ignored"],
     ["Oxygen taken in during breathing", "model-omits-component"],
     ["Water, which supplies the carbon", "model-omits-component"]], 0,
    "Cells rearrange existing carbon-based molecules; they do not create atoms. Sugar is the carbon source that other molecules are built from."),
  item("I-BIOLS17-01", "SCI-BIO-L018", "HS-LS1-7", "spiral_review",
    "What happens to the bonds during cellular respiration?",
    [["Bonds in sugar and oxygen break, and new, lower-energy bonds form in CO₂ and water", null],
     ["Bonds only break, and the energy is the leftover", "mechanism-missing"],
     ["Bonds only form, which is where the energy comes from", "mechanism-missing"],
     ["The sugar molecules are destroyed and their atoms disappear", "conservation-ignored"]], 0,
    "Energy is released because the new bonds are lower in energy than the old ones. Both breaking and forming happen, and every atom is accounted for."),
];

/** Chemistry · units 1-3 · atomic structure, bonding, and reactions */
const SCI_CHEM: DemoItem[] = [
  item("I-CHPS11-01", "SCI-CHEM-L001", "HS-PS1-1", "spiral_review",
    "Two elements sit in the same COLUMN of the periodic table. What do they share?",
    [["The number of outermost electrons, so they react similarly", null],
     ["The same number of protons", "model-omits-component"],
     ["The same atomic mass", "model-omits-component"],
     ["The same number of electron shells", "scale-confusion"]], 0,
    "A column is a group, and a group shares outer-electron count — which is what governs chemical behaviour. Rows share the number of shells."),
  item("I-CHPS13-01", "SCI-CHEM-L002", "HS-PS1-3", "spiral_review",
    "Substance A melts at 801 °C; substance B melts at −95 °C. What does that suggest?",
    [["The forces between A's particles are much stronger than between B's", null],
     ["A's particles are much heavier than B's", "mechanism-missing"],
     ["A is a larger molecule than B", "mechanism-missing"],
     ["B has stronger bonds inside its molecules", "model-omits-component"]], 0,
    "Melting point reflects the attraction BETWEEN particles, not the bonds inside them and not particle mass. More energy needed to separate means stronger attraction."),
  item("I-CHPS18-01", "SCI-CHEM-L003", "HS-PS1-8", "spiral_review",
    "What distinguishes a nuclear change from a chemical change?",
    [["The identity of the element itself can change", null],
     ["Energy is released", "mechanism-missing"],
     ["A gas is produced", "mechanism-missing"],
     ["The reaction is faster", "mechanism-missing"]], 0,
    "Chemical changes rearrange electrons and keep every nucleus intact. Nuclear changes alter the nucleus, so an atom of one element can become another."),
  item("I-CHPS12-01", "SCI-CHEM-L016", "HS-PS1-2", "spiral_review",
    "Sodium is in group 1 and chlorine is in group 17. What is the formula of the compound they form?",
    [["NaCl", null],
     ["Na₂Cl", "calculation"],
     ["NaCl₂", "calculation"],
     ["Na₁₇Cl", "representation"]], 0,
    "Sodium gives up one electron and chlorine takes one, so they combine one to one. The group numbers predict the charges, not the subscripts directly."),
];

/** Physics · units 1-2 · motion, forces, and Newton's laws */
const SCI_PHYS: DemoItem[] = [
  item("I-PHPS21-01", "SCI-PHYS-L001", "HS-PS2-1", "spiral_review",
    "A cart is pulled with a steady horizontal force on a frictionless track. What does its velocity-time graph look like?",
    [["A straight line with constant positive slope", null],
     ["A horizontal line", "mechanism-missing"],
     ["A curve that levels off", "mechanism-missing"],
     ["A line through the origin with zero slope", "representation"]], 0,
    "A steady net force gives a constant acceleration, and constant acceleration is a constant slope on a velocity-time graph. A horizontal line would mean no net force at all."),
  item("I-PHPS22-01", "SCI-PHYS-L017", "HS-PS2-2", "spiral_review",
    "Two skaters at rest push apart. One has twice the mass of the other. What is true just after the push?",
    [["The lighter skater moves away twice as fast", null],
     ["Both move away at the same speed", "conservation-ignored"],
     ["The heavier skater moves away twice as fast", "inverse-operation"],
     ["Neither moves, because the forces cancel", "force-pair-confusion"]], 0,
    "Total momentum stays zero, so the momenta are equal and opposite. Equal momentum with half the mass means twice the speed. The forces act on different objects, so they do not cancel."),
  item("I-PHPS23-01", "SCI-PHYS-L018", "HS-PS2-3", "spiral_review",
    "Why does a crumple zone reduce the force on passengers in a crash?",
    [["It extends the time over which the momentum changes", null],
     ["It reduces the car's momentum before impact", "mechanism-missing"],
     ["It makes the collision perfectly elastic", "mechanism-missing"],
     ["It absorbs the momentum so none reaches the passengers", "conservation-ignored"]], 0,
    "The same change in momentum spread over a longer time means a smaller average force. Momentum is not absorbed away; it is transferred more gently."),
];

/** Environmental Science · unit 1 · Earth systems thinking */
const SCI_ENV: DemoItem[] = [
  item("I-ENVESS21-01", "SCI-ENV-L001", "HS-ESS2-1", "spiral_review",
    "Which pair of processes builds mountains up and wears them down?",
    [["Plate motion builds; weathering and erosion wear down", null],
     ["Weathering builds; plate motion wears down", "mechanism-missing"],
     ["Both are driven only by surface water", "model-omits-component"],
     ["Both are driven only by heat inside Earth", "model-omits-component"]], 0,
    "Internal processes driven by Earth's heat build relief; surface processes driven by water, ice, and gravity remove it. The landscape you see is the balance between them."),
  item("I-ENVESS22-01", "SCI-ENV-L002", "HS-ESS2-2", "spiral_review",
    "Melting sea ice exposes darker ocean, which absorbs more sunlight and warms further. What kind of feedback is this?",
    [["Positive feedback — the change reinforces itself", null],
     ["Negative feedback — the change is damped", "mechanism-missing"],
     ["No feedback, because ice and ocean are separate systems", "model-omits-component"],
     ["A one-time effect with no ongoing loop", "mechanism-missing"]], 0,
    "Positive feedback amplifies the original change. It does not mean 'good' — it means the loop pushes in the same direction it started."),
  item("I-ENVESS24-01", "SCI-ENV-L004", "HS-ESS2-4", "spiral_review",
    "Which change would most directly alter how much solar energy Earth's surface absorbs?",
    [["A large change in the fraction of the surface covered by ice", null],
     ["A change in the length of an Earth day", "mechanism-missing"],
     ["A change in the tilt of the Moon's orbit", "mechanism-missing"],
     ["A change in the depth of the ocean floor", "mechanism-missing"]], 0,
    "Ice reflects; open water and land absorb. Changing the reflective fraction changes the energy the surface keeps."),
  item("I-ENVESS26-01", "SCI-ENV-L006", "HS-ESS2-6", "spiral_review",
    "Which is the largest reservoir of carbon on Earth over long timescales?",
    [["Rock, including limestone and fossil deposits", null],
     ["The atmosphere", "scale-confusion"],
     ["Living organisms", "scale-confusion"],
     ["Surface soil", "scale-confusion"]], 0,
    "By far the most carbon sits in rock. The atmosphere holds a small share — which is why moving even a little carbon out of rock changes it noticeably."),
  item("I-ENVESS27-01", "SCI-ENV-L007", "HS-ESS2-7", "spiral_review",
    "The rise of photosynthetic organisms changed Earth's atmosphere. What does that illustrate?",
    [["Life and Earth's systems have shaped each other over time", null],
     ["Earth's systems shape life, but not the reverse", "mechanism-missing"],
     ["Life shapes Earth's systems, but not the reverse", "mechanism-missing"],
     ["The two changed at the same time by coincidence", "correlation-as-cause"]], 0,
    "Coevolution runs both ways: organisms altered the atmosphere, and the altered atmosphere then selected which organisms could live in it."),
];

// ---------------------------------------------------------------------------
// English Language Arts
// ---------------------------------------------------------------------------

/** English 7 · units 1-2 · reading routines, evidence, and literary craft */
const ELA_07: DemoItem[] = [
  item("I-E7RL1-01", "ELA-07-L001", "RL.7.1", "spiral_review",
    "Which response best cites evidence for an inference?",
    [["She checked the door twice before sitting — she did not feel safe yet.", null],
     ["She did not feel safe.", "evidence-without-support"],
     ["'She checked the door twice.'", "quotation-without-commentary"],
     ["The story is about fear.", "topic-not-development"]], 0,
    "Evidence is the detail from the text; reasoning is the sentence that says what it shows. A quotation alone leaves the reader to guess your point."),
  item("I-E7RI1-01", "ELA-07-L003", "RI.7.1", "spiral_review",
    "An article states that a city's bus ridership fell after a fare rise. Which inference is best supported?",
    [["The fare rise may have discouraged some riders", null],
     ["The buses became less reliable", "ungrounded-inference"],
     ["The city wanted ridership to fall", "ungrounded-inference"],
     ["Ridership will keep falling next year", "ungrounded-inference"]], 0,
    "A supported inference stays close to what the text actually reports. The other three add causes and intentions the article never gives."),
  item("I-E7L4-01", "ELA-07-L006", "L.7.4", "spiral_review",
    "'The path was tortuous, winding back on itself again and again.' What does 'tortuous' mean here?",
    [["Full of twists and turns", null],
     ["Painful or agonising", "context-ignored"],
     ["Extremely long", "context-ignored"],
     ["Dangerous to walk", "ungrounded-inference"]], 0,
    "The clause after the comma defines the word. 'Torturous' is the similar-sounding word that means painful — the sentence itself rules it out."),
  item("I-E7SL1-01", "ELA-07-L005", "SL.7.1", "spiral_review",
    "Which move best builds on another speaker's idea in a discussion?",
    [["'You said the setting matters — where in the text do you see that?'", null],
     ["'I disagree, and here is my own point.'", "structure-vs-content"],
     ["'That is interesting.'", "evidence-without-support"],
     ["'We already covered that.'", "structure-vs-content"]], 0,
    "Building on an idea means engaging with it — asking for the evidence behind it, or extending it. Changing the subject politely is still changing the subject."),
  item("I-E7RL2-01", "ELA-07-L016", "RL.7.2", "spiral_review",
    "Which statement is a THEME rather than a summary?",
    [["Loyalty tested by distance can grow rather than fade.", null],
     ["Two friends write letters for a year and then meet.", "topic-not-development"],
     ["The story is about friendship.", "topic-not-development"],
     ["The letters are the most interesting part.", "evidence-without-support"]], 0,
    "A summary reports what happened; a theme claims something about a topic that the whole text supports."),
  item("I-E7RL4-01", "ELA-07-L018", "RL.7.4", "spiral_review",
    "A narrator describes a room as 'swallowing the light'. What does the word choice do?",
    [["Makes the room feel active and threatening", null],
     ["Tells the reader the room has no windows", "ungrounded-inference"],
     ["Shows the narrator is hungry", "context-ignored"],
     ["Describes the room's exact size", "context-ignored"]], 0,
    "'Swallowing' gives the room an appetite. Figurative language works by what it implies about mood, not by what it reports literally."),
];

/** English 11 · units 1-2 · evidence, theme, and craft */
const ELA_11: DemoItem[] = [
  item("I-E11RL1-01", "ELA-11-L001", "RL.11-12.1", "spiral_review",
    "A text never says whether the narrator forgave her brother. What is the strongest analytical move?",
    [["Name the uncertainty and show the details that keep it open", null],
     ["Choose the reading you prefer and defend it", "ungrounded-inference"],
     ["Say the author made a mistake", "ungrounded-inference"],
     ["Quote the last paragraph without comment", "quotation-without-commentary"]], 0,
    "At this level, analysis includes saying where the text leaves matters uncertain — and showing the evidence that keeps it that way."),
  item("I-E11RI1-01", "ELA-11-L003", "RI.11-12.1", "spiral_review",
    "An author writes: 'The policy succeeded, if success is measured only in cost.' What does the qualifier do?",
    [["Narrows the claim so it can be defended on one measure", null],
     ["Strengthens the claim by removing doubt", "structure-vs-content"],
     ["Shows the author opposes the policy entirely", "ungrounded-inference"],
     ["Adds a detail with no effect on the claim", "structure-vs-content"]], 0,
    "A qualifier limits what is being asserted. Reading past it turns a careful claim into a sweeping one the author did not make."),
  item("I-E11L4-01", "ELA-11-L006", "L.11-12.4", "spiral_review",
    "'The committee's response was perfunctory — three lines, sent within the hour.' What does 'perfunctory' mean?",
    [["Done as a routine duty, without real care", null],
     ["Prompt and efficient", "context-ignored"],
     ["Detailed and thorough", "context-ignored"],
     ["Angry and dismissive", "ungrounded-inference"]], 0,
    "The evidence after the dash — brief and fast — points at going through the motions, not at speed as a virtue and not at anger."),
  item("I-E11RL2-01", "ELA-11-L016", "RL.11-12.2", "spiral_review",
    "A novel develops both 'inherited guilt' and 'the cost of silence'. What does analysing their INTERACTION require?",
    [["Showing where one theme complicates or deepens the other", null],
     ["Deciding which theme is the real one", "topic-not-development"],
     ["Summarising each theme separately", "topic-not-development"],
     ["Counting how often each is mentioned", "evidence-without-support"]], 0,
    "Two themes interact when the text uses one to press on the other. Treating them as a list misses the relationship the question asks about."),
  item("I-E11RL4-01", "ELA-11-L018", "RL.11-12.4", "spiral_review",
    "An author repeatedly calls a factory 'the works'. What is the most likely effect?",
    [["It makes the place sound impersonal and total", null],
     ["It tells the reader what the factory produces", "context-ignored"],
     ["It shows the narrator admires the factory", "ungrounded-inference"],
     ["It has no effect, because it is only a name", "structure-vs-content"]], 0,
    "Repeated word choice accumulates. A definite article plus an abstract noun strips the place of anything individual, which is the point."),
  item("I-E11RL5-01", "ELA-11-L019", "RL.11-12.5", "spiral_review",
    "A story opens with its ending and then works backwards. What does that structure do?",
    [["Shifts attention from what happens to why it happened", null],
     ["Makes the story harder to follow, with no other effect", "structure-vs-content"],
     ["Proves the narrator is unreliable", "ungrounded-inference"],
     ["Shortens the story", "structure-vs-content"]], 0,
    "Structure is a choice with consequences. Removing suspense about the outcome moves the reader's attention onto cause."),
];

/** English 12 · units 1-2 · discussion, character, and point of view */
const ELA_12: DemoItem[] = [
  item("I-E12SL1-01", "ELA-12-L005", "SL.11-12.1", "spiral_review",
    "What does coming to a discussion PREPARED look like at this level?",
    [["Having read the text and marked the passages you plan to raise", null],
     ["Having an opinion ready to defend", "evidence-without-support"],
     ["Having read a summary of the text", "evidence-without-support"],
     ["Waiting to hear what others think first", "structure-vs-content"]], 0,
    "Preparation is about the evidence you bring, not the position you hold. Marked passages let a discussion move on the text rather than around it."),
  item("I-E12RL3-01", "ELA-12-L017", "RL.11-12.3", "spiral_review",
    "An author introduces a character only through what other people say about her. What does that choice do?",
    [["Makes her reputation, rather than her actions, the subject", null],
     ["Shows that she is dishonest", "ungrounded-inference"],
     ["Proves she is a minor character", "structure-vs-content"],
     ["Keeps the story shorter", "structure-vs-content"]], 0,
    "How an author chooses to introduce and develop a character is itself a claim. Withholding direct action puts the focus on how she is perceived."),
  item("I-E12RL6-01", "ELA-12-L020", "RL.11-12.6", "spiral_review",
    "A narrator insists he was 'perfectly calm' while describing his shaking hands. What is going on?",
    [["The text means something different from what the narrator says", null],
     ["The narrator is lying to another character", "ungrounded-inference"],
     ["The author made a continuity error", "ungrounded-inference"],
     ["The detail about the hands is decoration", "structure-vs-content"]], 0,
    "Distinguishing what is directly stated from what is really meant is the point of the standard. The gap between claim and detail is where irony lives."),
];

// ---------------------------------------------------------------------------
// History-Social Science
// ---------------------------------------------------------------------------

/** Grade 7 Medieval/Early Modern World · units 1-2 */
const HSS_07: DemoItem[] = [
  item("I-H7-111-01", "HSS-07-L001", "HSS.7.1.1", "spiral_review",
    "Which is a LASTING contribution of Rome rather than a feature of its own era only?",
    [["Legal principles such as the right to a defence", null],
     ["The size of the Roman army", "principle-vs-example"],
     ["The reign of a particular emperor", "principle-vs-example"],
     ["The population of the city of Rome", "principle-vs-example"]], 0,
    "A lasting contribution is one later societies adopted. Roman legal ideas outlived the empire; the army and its emperors did not."),
  item("I-H7-112-01", "HSS-07-L002", "HSS.7.1.2", "spiral_review",
    "Which best explains why Rome's size threatened its territorial cohesion?",
    [["Distant frontiers were slow and costly to defend and administer", null],
     ["Romans stopped building roads", "mechanism-missing"],
     ["The empire ran out of land to conquer", "single-cause"],
     ["Latin was replaced as the official language", "mechanism-missing"]], 0,
    "Scale is the mechanism: the further the frontier, the longer the supply line and the slower any response. That is a structural pressure, not a single event."),
  item("I-H7-113-01", "HSS-07-L003", "HSS.7.1.3", "spiral_review",
    "Why did Constantine's new capital matter for what came after Rome?",
    [["Constantinople carried Roman law and administration onward for centuries", null],
     ["It ended the Roman empire immediately", "no-temporal-relationship"],
     ["It moved the empire outside Europe entirely", "mechanism-missing"],
     ["It had no effect beyond Constantine's own reign", "no-temporal-relationship"]], 0,
    "The eastern empire continued as Byzantium long after the western one fell — which is why Roman institutions survived to influence later states."),
  item("I-H7-721-01", "HSS-07-L016", "HSS.7.2.1", "spiral_review",
    "How did the physical geography of the Arabian peninsula shape ways of life there?",
    [["Scarce water supported nomadic herding alongside settled oasis and coastal towns", null],
     ["Abundant rivers made large farming empires the only option", "mechanism-missing"],
     ["Its isolation prevented any contact with other regions", "mechanism-missing"],
     ["Mountains kept the whole peninsula cool and wet", "mechanism-missing"]], 0,
    "Aridity is the constraint. It made mobility valuable, while oases and ports supported settlement and long-distance trade at the same time."),
  item("I-H7-722-01", "HSS-07-L017", "HSS.7.2.2", "spiral_review",
    "Which statement about Islam's relationship to Judaism and Christianity is accurate?",
    [["It recognises earlier prophets shared with both traditions", null],
     ["It developed with no knowledge of either", "mechanism-missing"],
     ["It replaced both in the regions where it spread, everywhere and at once", "no-temporal-relationship"],
     ["It shares no figures or teachings with either", "mechanism-missing"]], 0,
    "Islamic teaching places itself in the same prophetic line, which is one reason the three traditions share figures and stories."),
];

/** Grade 8 U.S. Growth and Conflict · units 1-2 */
const HSS_08: DemoItem[] = [
  item("I-H8-812-01", "HSS-08-L002", "HSS.8.1.2", "spiral_review",
    "According to the Declaration of Independence, what is government FOR?",
    [["Securing rights people already hold", null],
     ["Granting rights to the people", "principle-vs-example"],
     ["Maintaining the authority of the monarch", "principle-vs-example"],
     ["Managing the economy", "principle-vs-example"]], 0,
    "The Declaration treats rights as unalienable and pre-existing; government derives its just powers from consent in order to secure them. Granting is exactly what it denies."),
  item("I-H8-822-01", "HSS-08-L006", "HSS.8.2.2", "spiral_review",
    "What was the central weakness of the Articles of Confederation?",
    [["The national government could not tax or enforce its own decisions", null],
     ["There was no written document at all", "mechanism-missing"],
     ["States were forbidden to have their own laws", "mechanism-missing"],
     ["It gave the president too much power", "institution-confused"]], 0,
    "Without the power to raise revenue or compel compliance, the confederation could ask but not act. There was no president under the Articles."),
  item("I-H8-824-01", "HSS-08-L008", "HSS.8.2.4", "spiral_review",
    "What were the Federalist Papers written to do?",
    [["Argue for ratifying the proposed Constitution", null],
     ["Record the debates at the Convention", "source-vs-claim"],
     ["Serve as the first draft of the Bill of Rights", "source-vs-claim"],
     ["Explain the Articles of Confederation to Europe", "source-vs-claim"]], 0,
    "They are persuasive essays aimed at ratification, chiefly in New York. Reading them as neutral minutes mistakes an argument for a record."),
  item("I-H8-827-01", "HSS-08-L011", "HSS.8.2.7", "spiral_review",
    "Which describes CHECKS AND BALANCES rather than separation of powers?",
    [["Congress can override a veto, and the Senate confirms judges", null],
     ["Legislative, executive, and judicial powers sit in different branches", "principle-vs-example"],
     ["States keep powers not given to the national government", "institution-confused"],
     ["Citizens elect representatives", "institution-confused"]], 0,
    "Separation puts the powers in different hands; checks and balances let each branch limit the others. The third option describes federalism."),
  item("I-H8-833-01", "HSS-08-L014", "HSS.8.3.3", "spiral_review",
    "What is the relationship between the Constitution's enumerated powers and the Bill of Rights?",
    [["One grants powers to government; the other limits what government may do", null],
     ["Both grant powers to government", "principle-vs-example"],
     ["Both list rights held by citizens", "principle-vs-example"],
     ["The Bill of Rights replaced the enumerated powers", "no-temporal-relationship"]], 0,
    "They work in opposite directions on purpose: enumerated powers say what government may do, and the amendments say what it may not."),
  item("I-H8-841-01", "HSS-08-L016", "HSS.8.4.1", "spiral_review",
    "The Louisiana Purchase raised a constitutional question for Jefferson. Why?",
    [["The Constitution did not clearly authorise buying territory", null],
     ["It required a declaration of war", "institution-confused"],
     ["It needed approval from the Supreme Court first", "institution-confused"],
     ["Only states could purchase land", "institution-confused"]], 0,
    "Jefferson read federal power narrowly, and no enumerated power covered acquiring territory — which is why the purchase troubled him despite its advantages."),
];

/** Human Geography · units 1-2 · spatial thinking and population */
const HSS_HGEO: DemoItem[] = [
  item("I-HG-1-01", "HSS-HGEO-L001", "HSS.FW14.HGEO.1", "spiral_review",
    "Every world map distorts something. Why?",
    [["A curved surface cannot be flattened without stretching or tearing", null],
     ["Map-makers disagree about borders", "mechanism-missing"],
     ["Satellites cannot photograph the whole Earth at once", "mechanism-missing"],
     ["Paper is not large enough", "mechanism-missing"]], 0,
    "Projection is a geometric problem, not a political or technical one. Every projection chooses which property — area, shape, distance, direction — to preserve."),
  item("I-HG-10-01", "HSS-HGEO-L002", "HSS.FW14.HGEO.10", "spiral_review",
    "Which is a FUNCTIONAL region rather than a formal one?",
    [["The delivery area of a city newspaper", null],
     ["A country's national borders", "region-type-confused"],
     ["An area where one language is spoken by nearly everyone", "region-type-confused"],
     ["A climate zone on a map", "region-type-confused"]], 0,
    "A functional region is organised around a node and its activity. A formal region is defined by a shared measurable trait such as language, climate, or law."),
  item("I-HG-2-01", "HSS-HGEO-L016", "HSS.FW14.HGEO.2", "spiral_review",
    "Two countries have the same population. One has far more people per square kilometre. What does that tell you?",
    [["Its population is concentrated in a smaller habitable area", null],
     ["It has more people", "scale-confusion"],
     ["It is growing faster", "scale-confusion"],
     ["Its people are poorer", "ungrounded-inference"]], 0,
    "Density relates people to land, not to totals, growth, or wealth. The same population in less usable space produces a higher density."),
];

/** Modern World History · units 1-2 · democratic traditions and industrialization */
const HSS_MWH: DemoItem[] = [
  item("I-H10-112-01", "HSS-MWH-L002", "HSS.10.1.2", "spiral_review",
    "What is the core idea of 'the rule of law' as it developed in Western political thought?",
    [["Rulers are bound by the same law as those they govern", null],
     ["Laws should be written down", "principle-vs-example"],
     ["The majority decides every question", "principle-vs-example"],
     ["Courts should be independent of the monarch", "principle-vs-example"]], 0,
    "Written law, majority rule, and independent courts are mechanisms that can serve it, but the principle itself is that no one stands above the law."),
  item("I-H10-121-01", "HSS-MWH-L004", "HSS.10.2.1", "spiral_review",
    "Which idea is most associated with Montesquieu's influence on later constitutions?",
    [["Dividing government power among separate branches", null],
     ["Government by consent of the governed", "principle-vs-example"],
     ["The general will of the people", "principle-vs-example"],
     ["Natural rights to life, liberty, and property", "principle-vs-example"]], 0,
    "Separation of powers is Montesquieu's contribution. Consent and natural rights are Locke's; the general will is Rousseau's."),
  item("I-H10-122-01", "HSS-MWH-L005", "HSS.10.2.2", "spiral_review",
    "What do the Magna Carta and the English Bill of Rights have in common?",
    [["Both limited what the monarch could do without consent", null],
     ["Both established universal suffrage", "presentism"],
     ["Both abolished the monarchy", "presentism"],
     ["Both created a written constitution for England", "institution-confused"]], 0,
    "Each constrained royal power at a particular moment. Neither extended the vote broadly, and England still has no single written constitution."),
  item("I-H10-124-01", "HSS-MWH-L007", "HSS.10.2.4", "spiral_review",
    "Which sequence describes France after 1789?",
    [["Constitutional monarchy, then radical republic, then Napoleonic empire", null],
     ["Napoleonic empire, then constitutional monarchy, then republic", "no-temporal-relationship"],
     ["Republic, then monarchy restored, with no empire", "no-temporal-relationship"],
     ["Empire throughout, under different names", "no-temporal-relationship"]], 0,
    "The order matters: the revolution first limited the crown, then removed it, and the instability that followed opened the way to Napoleon."),
  item("I-H10-131-01", "HSS-MWH-L016", "HSS.10.3.1", "spiral_review",
    "Which combination best explains why England industrialised first?",
    [["Coal and iron, capital and banking, and a workforce moving off the land", null],
     ["A single inventor's breakthrough", "single-cause"],
     ["A larger population than anywhere else", "single-cause"],
     ["A government order requiring factories", "mechanism-missing"]], 0,
    "Industrialisation needed several conditions at once. A single-cause answer names one ingredient and calls it the recipe."),
  item("I-H10-133-01", "HSS-MWH-L018", "HSS.10.3.3", "spiral_review",
    "Why did cities grow so quickly during industrialisation?",
    [["Factory work drew people from the countryside faster than housing could follow", null],
     ["Birth rates in cities suddenly rose above rural ones", "mechanism-missing"],
     ["Governments required people to move to cities", "mechanism-missing"],
     ["Farming was banned near the new factories", "mechanism-missing"]], 0,
    "Migration, not birth rate, drove the surge — and the mismatch between arrivals and housing is what produced the conditions reformers later attacked."),
];

/** US History · units 1-2 · founding ideals and industrialization */
const HSS_US: DemoItem[] = [
  item("I-H11-111-01", "HSS-US-L001", "HSS.11.1.1", "spiral_review",
    "Which Enlightenment idea most directly shaped the founding documents?",
    [["Government exists by consent to protect natural rights", null],
     ["Monarchs rule by divine right", "principle-vs-example"],
     ["Wealth should be distributed equally by the state", "presentism"],
     ["Religion should determine who may hold office", "principle-vs-example"]], 0,
    "Consent and natural rights are the through-line from Enlightenment thought to the Declaration and the Constitution."),
  item("I-H11-112-01", "HSS-US-L002", "HSS.11.1.2", "spiral_review",
    "Why was the Bill of Rights added to the Constitution?",
    [["Ratification depended on assurances that individual liberties would be protected", null],
     ["The Supreme Court ordered it", "institution-confused"],
     ["It was written before the Constitution and attached later", "no-temporal-relationship"],
     ["It replaced the Articles of Confederation", "no-temporal-relationship"]], 0,
    "Anti-Federalist objections in the state ratifying conventions made explicit protections the price of ratification."),
  item("I-H11-114-01", "HSS-US-L004", "HSS.11.1.4", "spiral_review",
    "Which pairing best describes an effect of Reconstruction?",
    [["Constitutional amendments extended rights that later enforcement narrowed", null],
     ["Reconstruction ended slavery, and nothing else changed", "single-cause"],
     ["Reconstruction had no constitutional consequences", "mechanism-missing"],
     ["Reconstruction restored the prewar order exactly", "no-temporal-relationship"]], 0,
    "The Thirteenth, Fourteenth, and Fifteenth Amendments changed the constitutional text; what happened to their enforcement afterwards is a separate story."),
  item("I-H11-121-01", "HSS-US-L016", "HSS.11.2.1", "spiral_review",
    "What made Upton Sinclair's The Jungle politically consequential?",
    [["Its account of unsafe conditions moved public opinion toward federal regulation", null],
     ["It was written by a government inspector", "source-vs-claim"],
     ["It was a neutral statistical report", "source-vs-claim"],
     ["It described conditions after regulation had already been passed", "no-temporal-relationship"]], 0,
    "It is an argument in the form of a novel, and its effect ran through public reaction to federal food-safety law."),
  item("I-H11-124-01", "HSS-US-L019", "HSS.11.2.4", "spiral_review",
    "Why did urban political machines retain support among immigrant communities?",
    [["They delivered jobs, services, and help in exchange for votes", null],
     ["They had no rivals in city politics", "mechanism-missing"],
     ["They were required by state law", "institution-confused"],
     ["They were led by reformers", "institution-confused"]], 0,
    "The exchange was concrete and immediate at a time when formal relief barely existed — which is exactly what made reformers' attacks difficult."),
  item("I-H11-125-01", "HSS-US-L020", "HSS.11.2.5", "spiral_review",
    "What did a trust allow industrial leaders to do?",
    [["Combine competing firms under common control to limit competition", null],
     ["Borrow money from the federal government", "institution-confused"],
     ["Guarantee workers a share of the profits", "presentism"],
     ["Set wages by law", "institution-confused"]], 0,
    "Consolidation was the point: fewer independent competitors meant more control over price and supply, which is what antitrust law was written against."),
];

/** Government · unit 1 · democratic foundations */
const HSS_GOV: DemoItem[] = [
  item("I-HGOV-111-01", "HSS-GOV-L001", "HSS.GOV.12.1.1", "spiral_review",
    "Which idea did John Locke contribute most directly to American government?",
    [["Government by consent, to protect life, liberty, and property", null],
     ["Separation of powers among three branches", "principle-vs-example"],
     ["The general will as the source of law", "principle-vs-example"],
     ["Rule by a single strong prince", "principle-vs-example"]], 0,
    "Locke supplied consent and natural rights; Montesquieu supplied separation of powers, and Rousseau the general will."),
  item("I-HGOV-113-01", "HSS-GOV-L003", "HSS.GOV.12.1.3", "spiral_review",
    "The Constitution balances two older traditions. Which pair?",
    [["Classical republican concern for the public good, and liberal protection of individual rights", null],
     ["Direct democracy and hereditary monarchy", "principle-vs-example"],
     ["Federalism and free trade", "institution-confused"],
     ["Judicial review and civilian control of the military", "principle-vs-example"]], 0,
    "The two traditions pull in different directions — collective good and individual liberty — and the document tries to hold both."),
  item("I-HGOV-114-01", "HSS-GOV-L004", "HSS.GOV.12.1.4", "spiral_review",
    "The Federalist Papers argue that government must be limited because of what?",
    [["A realistic view of human nature, including those who govern", null],
     ["A belief that people are naturally good", "principle-vs-example"],
     ["A wish to keep the states weak", "institution-confused"],
     ["A plan to expand federal power gradually", "institution-confused"]], 0,
    "'If men were angels, no government would be necessary.' Limits exist because power is held by people who can misuse it."),
  item("I-HGOV-115-01", "HSS-GOV-L005", "HSS.GOV.12.1.5", "spiral_review",
    "Federalist No. 10 addresses which problem?",
    [["How a large republic can control the effects of faction", null],
     ["How judges should be appointed", "institution-confused"],
     ["How the military should be commanded", "institution-confused"],
     ["How states should be admitted to the union", "institution-confused"]], 0,
    "Madison argues that a larger republic makes any single faction less likely to command a majority. Judicial independence is No. 78."),
  item("I-HGOV-116-01", "HSS-GOV-L006", "HSS.GOV.12.1.6", "spiral_review",
    "What does the Bill of Rights do?",
    [["Limits what government may do to individuals", null],
     ["Lists the duties citizens owe the government", "principle-vs-example"],
     ["Grants the federal government its powers", "principle-vs-example"],
     ["Establishes the three branches", "institution-confused"]], 0,
    "The amendments are restraints on government, not grants of power and not a list of obligations."),
  item("I-HGOV-1210-01", "HSS-GOV-L007", "HSS.GOV.12.10", "spiral_review",
    "Which pair names a genuine tension inside a constitutional democracy?",
    [["Majority rule and individual rights", null],
     ["Voting and elections", "principle-vs-example"],
     ["Laws and courts", "principle-vs-example"],
     ["Taxes and spending", "institution-confused"]], 0,
    "A majority can vote to restrict a minority's rights, which is precisely why rights are placed beyond ordinary majorities. The other pairs are not in tension."),
];


/** English 8 · units 1-2 · evidence, vocabulary, and literary craft */
const ELA_08: DemoItem[] = [
  item("I-E8RI1-01", "ELA-08-L003", "RI.8.1", "spiral_review",
    "A report says a library's evening visits rose after it added late hours. Which inference is best supported?",
    [["Some visitors used hours that were not previously available", null],
     ["The library's daytime service got worse", "ungrounded-inference"],
     ["People read more books than before", "ungrounded-inference"],
     ["The change will keep visits rising every year", "ungrounded-inference"]], 0,
    "A supported inference stays inside what the text reports. The others add causes and outcomes the report never gives."),
  item("I-E8L4-01", "ELA-08-L006", "L.8.4", "spiral_review",
    "'The evidence was scant — one photograph and a half-remembered date.' What does 'scant' mean?",
    [["Barely enough", null],
     ["Convincing", "context-ignored"],
     ["Recently found", "context-ignored"],
     ["Carefully checked", "context-ignored"]], 0,
    "The two examples after the dash are thin, and the dash marks them as the definition. The sentence supplies the meaning."),
  item("I-E8SL1-01", "ELA-08-L005", "SL.8.1", "spiral_review",
    "Which response most helps a discussion move forward?",
    [["'Where in the text do you see that?'", null],
     ["'I think you are wrong.'", "structure-vs-content"],
     ["'Good point.'", "evidence-without-support"],
     ["'Let's move on.'", "structure-vs-content"]], 0,
    "Asking for the evidence keeps the discussion on the text. Agreement and disagreement without evidence leave it on opinion."),
  item("I-E8RL3-01", "ELA-08-L017", "RL.8.3", "spiral_review",
    "A character who has avoided the sea all book finally rows out alone. What does that moment do?",
    [["Reveals a change in the character by breaking an established pattern", null],
     ["Shows the author needed an ending", "structure-vs-content"],
     ["Proves the sea is a symbol of danger", "ungrounded-inference"],
     ["Adds description without changing anything", "structure-vs-content"]], 0,
    "Dialogue and incident reveal character. A break from an established pattern is the text showing a change rather than announcing it."),
];

/** English 9 · units 1-2 · evidence, vocabulary, and structure */
const ELA_09: DemoItem[] = [
  item("I-E9RI1-01", "ELA-09-L003", "RI.9-10.1", "spiral_review",
    "An article reports that a policy 'coincided with' a fall in emissions. What does the phrasing signal?",
    [["The author is claiming timing, not cause", null],
     ["The author is claiming the policy worked", "correlation-as-cause"],
     ["The author opposes the policy", "ungrounded-inference"],
     ["The two facts are unrelated", "ungrounded-inference"]], 0,
    "'Coincided with' places two things in the same period without asserting a link. Reading it as cause adds a claim the writer avoided."),
  item("I-E9L4-01", "ELA-09-L006", "L.9-10.4", "spiral_review",
    "'The plan was untenable: it needed more money than the town would ever raise.' What does 'untenable' mean?",
    [["Impossible to maintain or defend", null],
     ["Expensive but workable", "context-ignored"],
     ["Unpopular with voters", "ungrounded-inference"],
     ["Not yet finished", "context-ignored"]], 0,
    "The colon introduces the reason: the plan cannot be held up. Cost is the evidence, not the meaning."),
  item("I-E9SL1-01", "ELA-09-L005", "SL.9-10.1", "spiral_review",
    "In a text-based discussion, what does a strong disagreement look like?",
    [["Naming the passage that led you to a different reading", null],
     ["Restating your position more firmly", "evidence-without-support"],
     ["Pointing out that the other speaker often misreads", "structure-vs-content"],
     ["Waiting until the discussion ends to object", "structure-vs-content"]], 0,
    "Disagreement is productive when it is anchored in the text. Repetition and personal comments move the discussion away from evidence."),
  item("I-E9RL5-01", "ELA-09-L019", "RL.9-10.5", "spiral_review",
    "An author breaks a chapter into very short sections with white space between them. What effect is most likely?",
    [["It slows the reader and isolates each moment", null],
     ["It shows the narrator is unreliable", "ungrounded-inference"],
     ["It proves the chapter is unfinished", "structure-vs-content"],
     ["It has no effect, because the words are the same", "structure-vs-content"]], 0,
    "Structure is a choice with consequences. Where an author puts the breaks controls the pace at which a reader takes the chapter in."),
];

/** Mathematics 8 · units 1-2 · real numbers, exponents, and slope */
const MATH_08_EXTRA: DemoItem[] = [
  item("I-M8NS1-01", "MATH-08-L001", "8.NS.1", "spiral_review",
    "Which number is irrational?",
    [["√7", null],
     ["0.75", "representation"],
     ["√9", "representation"],
     ["2/3", "representation"]], 0,
    "An irrational number cannot be written as a ratio of integers and its decimal never repeats. √9 is 3, and 0.75 and 2/3 are both ratios."),
  item("I-M8NS2-01", "MATH-08-L002", "8.NS.2", "spiral_review",
    "Between which two whole numbers does √30 lie?",
    [["5 and 6", null],
     ["4 and 5", "calculation"],
     ["6 and 7", "calculation"],
     ["14 and 16", "inverse-operation"]], 0,
    "5² = 25 and 6² = 36, and 30 sits between them. Halving instead of taking a root gives 15, which answers a different question."),
  item("I-M8EE3-01", "MATH-08-L005", "8.EE.3", "spiral_review",
    "About how many times larger is 6 × 10⁸ than 3 × 10⁵?",
    [["2,000 times", null],
     ["2 times", "unit-and-scale"],
     ["3 times", "calculation"],
     ["200 times", "calculation"]], 0,
    "Divide the coefficients and subtract the exponents: 2 × 10³ = 2,000. Comparing only the coefficients ignores the order of magnitude, which is the whole point of the notation."),
  item("I-M8EE5-01", "MATH-08-L016", "8.EE.5", "spiral_review",
    "Two proportional lines are graphed. Line A passes through (2, 6); line B through (3, 6). Which has the greater unit rate?",
    [["Line A, at 3 per unit against B's 2", null],
     ["Line B, because it reaches 6 later", "inverse-operation"],
     ["They are equal, because both reach 6", "proportional-vs-additive"],
     ["It cannot be told without more points", "no-verification"]], 0,
    "For a proportional line the unit rate is the slope: 6/2 = 3 and 6/3 = 2. Reaching the same height further along means a gentler slope."),
  item("I-M8EE6-01", "MATH-08-L017", "8.EE.6", "spiral_review",
    "Why is the slope between any two points on a straight line the same?",
    [["The right triangles formed between any two points are similar", null],
     ["Because the line passes through the origin", "theorem-misapplied"],
     ["Because the points are equally spaced", "theorem-misapplied"],
     ["It is not the same; it changes along the line", "representation"]], 0,
    "Similar triangles have proportional sides, so rise over run is constant. That is the argument behind writing a line as y = mx + b."),
];

/** Math 2 · units 1-2 · rational exponents, complex numbers, and quadratics */
const MATH_2: DemoItem[] = [
  item("I-M2NRN1-01", "MATH-2-L001", "N-RN.1", "spiral_review",
    "What does x^(1/3) mean?",
    [["The cube root of x", null],
     ["x divided by 3", "inverse-operation"],
     ["One third of x", "inverse-operation"],
     ["x cubed", "inverse-operation"]], 0,
    "The exponent rules force it: (x^(1/3))³ = x^(3/3) = x, and the number whose cube is x is the cube root."),
  item("I-M2NRN2-01", "MATH-2-L002", "N-RN.2", "spiral_review",
    "Rewrite √(x³) using a rational exponent.",
    [["x^(3/2)", null],
     ["x^(2/3)", "inverse-operation"],
     ["x^(1/3)", "calculation"],
     ["x^(6)", "calculation"]], 0,
    "The index of the root is the denominator and the power is the numerator: a square root of x³ is x^(3/2)."),
  item("I-M2NRN3-01", "MATH-2-L003", "N-RN.3", "spiral_review",
    "What kind of number is the sum of a rational number and an irrational number?",
    [["Always irrational", null],
     ["Always rational", "theorem-misapplied"],
     ["Sometimes rational, sometimes irrational", "theorem-misapplied"],
     ["Always an integer", "theorem-misapplied"]], 0,
    "If the sum were rational, subtracting the rational part would make the irrational number rational — a contradiction."),
  item("I-M2NCN1-01", "MATH-2-L004", "N-CN.1", "spiral_review",
    "What is i²?",
    [["−1", null],
     ["1", "sign"],
     ["i", "theorem-misapplied"],
     ["0", "theorem-misapplied"]], 0,
    "i is defined as the number whose square is −1. That single definition is what the whole complex number system is built on."),
  item("I-M2NCN2-01", "MATH-2-L005", "N-CN.2", "spiral_review",
    "Simplify (2 + 3i) + (4 − i).",
    [["6 + 2i", null],
     ["6 + 4i", "sign"],
     ["6 + 2", "representation"],
     ["8i", "distribution-and-like-terms"]], 0,
    "Add the real parts and the imaginary parts separately, like combining like terms: 2 + 4 = 6, and 3i − i = 2i."),
  item("I-M2ASSE1a-01", "MATH-2-L016", "A-SSE.1.a", "spiral_review",
    "In the expression 5(x + 3)², what is the factor 5 doing?",
    [["Scaling the whole squared quantity", null],
     ["Adding 5 to the result", "variable-interpretation"],
     ["Being squared along with (x + 3)", "distribution-and-like-terms"],
     ["Multiplying only the x", "distribution-and-like-terms"]], 0,
    "The exponent binds to (x + 3) alone, so 5 multiplies whatever that squares to. Treating 5 as part of the base changes the expression."),
];


/** English 6 · unit 1 · reading routines, vocabulary, and discussion */
const ELA_06: DemoItem[] = [
  item("I-E6RI1-01", "ELA-06-L003", "RI.6.1", "spiral_review",
    "An article states that a park's visitor numbers doubled after a new path opened. What can you infer with support?",
    [["The path may have made the park easier to reach or use", null],
     ["The park became the most popular in the city", "ungrounded-inference"],
     ["The old path was dangerous", "ungrounded-inference"],
     ["Visitors will keep doubling each year", "ungrounded-inference"]], 0,
    "A supported inference stays close to what the article reports. The others add facts the text never gives."),
  item("I-E6L4-01", "ELA-06-L006", "L.6.4", "spiral_review",
    "'The room was sparse: one chair, one lamp, nothing on the walls.' What does 'sparse' mean?",
    [["Having very little in it", null],
     ["Tidy and well organised", "context-ignored"],
     ["Large and open", "context-ignored"],
     ["Recently cleaned", "ungrounded-inference"]], 0,
    "The list after the colon is the definition. Tidy and empty are not the same thing, and the sentence points at empty."),
  item("I-E6SL1-01", "ELA-06-L005", "SL.6.1", "spiral_review",
    "What does it mean to build on someone else's idea in a discussion?",
    [["Adding evidence or a question that takes their point further", null],
     ["Repeating what they said in your own words", "structure-vs-content"],
     ["Saying you agree", "evidence-without-support"],
     ["Starting a new topic", "structure-vs-content"]], 0,
    "Building on an idea moves it along. Repeating and agreeing leave it exactly where it was."),
];

/** Integrated Science 6 · units 1-2 · cells and body systems */
const SCI_06_EXTRA: DemoItem[] = [
  item("I-S6LS12-01", "SCI-06-L002", "MS-LS1-2", "spiral_review",
    "What is the function of a cell membrane?",
    [["Controlling what enters and leaves the cell", null],
     ["Storing the cell's genetic information", "model-omits-component"],
     ["Releasing energy from food", "model-omits-component"],
     ["Giving the cell its rigid shape in every organism", "model-omits-component"]], 0,
    "The membrane is the boundary that regulates exchange. Genetic information sits in the nucleus, and energy release happens in the mitochondria."),
  item("I-S6LS13-01", "SCI-06-L003", "MS-LS1-3", "spiral_review",
    "Which describes how body systems interact?",
    [["The circulatory system carries oxygen the respiratory system takes in", null],
     ["Each system works entirely on its own", "model-omits-component"],
     ["The digestive system supplies oxygen to cells", "model-omits-component"],
     ["Systems only interact when a person is ill", "mechanism-missing"]], 0,
    "Systems are interdependent by design. Oxygen enters at the lungs and is delivered by the blood — two systems doing one job."),
  item("I-S6LS14-01", "SCI-06-L016", "MS-LS1-4", "spiral_review",
    "Bright petals and nectar in flowering plants are best explained by what?",
    [["They increase the chance of successful reproduction by attracting pollinators", null],
     ["They protect the plant from being eaten", "mechanism-missing"],
     ["They help the plant absorb more sunlight", "mechanism-missing"],
     ["They store water for dry periods", "mechanism-missing"]], 0,
    "The characteristic is explained by what it does for reproduction. Defence, light, and water storage are jobs other structures do."),
];

/** Math 1 · units 1-2 · quantities, expression structure, and equations */
const MATH_1_EXTRA: DemoItem[] = [
  item("I-M1NQ3-01", "MATH-1-L003", "N-Q.3", "spiral_review",
    "A tape measure reads to the nearest centimetre. How should a length of about 2 m be reported?",
    [["203 cm — no more precision than the tool gives", null],
     ["203.47 cm, to be as precise as possible", "unit-and-scale"],
     ["2 m, because that is the round figure", "unit-and-scale"],
     ["Any value, since precision does not matter for length", "no-verification"]], 0,
    "Reported precision should match the instrument. Extra decimal places claim accuracy the measurement does not have."),
  item("I-M1ASSE1b-01", "MATH-1-L017", "A-SSE.1.b", "spiral_review",
    "In P(1 + r)ⁿ, what does the whole factor (1 + r)ⁿ represent?",
    [["The total growth factor after n periods", null],
     ["The amount added in one period", "variable-interpretation"],
     ["The number of periods", "variable-interpretation"],
     ["The starting amount", "variable-interpretation"]], 0,
    "Reading an expression by its parts: P is the start, and everything raised to the n is what multiplies it over n periods."),
  item("I-M1ACED2-01", "MATH-1-L019", "A-CED.2", "spiral_review",
    "A gym charges $30 to join and $12 a month. Which equation gives total cost c after m months?",
    [["c = 12m + 30", null],
     ["c = 30m + 12", "variable-interpretation"],
     ["c = 42m", "proportional-vs-additive"],
     ["c = 12m − 30", "sign"]], 0,
    "The one-off charge is a constant; the monthly charge multiplies the months. Combining them into a single rate charges the joining fee every month."),
  item("I-M1AREI1-01", "MATH-1-L022", "A-REI.1", "spiral_review",
    "Why is it valid to add the same number to both sides of an equation?",
    [["It preserves the equality, so the solutions do not change", null],
     ["It simplifies the arithmetic", "equality-and-equivalence"],
     ["It is a rule with no reason behind it", "equality-and-equivalence"],
     ["It works only when both sides are positive", "equality-and-equivalence"]], 0,
    "Each step in solving is justified by keeping the two sides equal. That is what guarantees the answer at the end is an answer to the original question."),
];

/** Every added recall bank, in one list. */
export const RECALL_BANKS: readonly DemoItem[] = [
  ...MATH_1_EXTRA,
  ...MATH_07,
  ...MATH_08_EXTRA,
  ...MATH_2,
  ...MATH_3,
  ...MATH_STATS,
  ...SCI_06_EXTRA,
  ...SCI_07,
  ...SCI_08,
  ...SCI_BIO,
  ...SCI_CHEM,
  ...SCI_PHYS,
  ...SCI_ENV,
  ...ELA_06,
  ...ELA_07,
  ...ELA_08,
  ...ELA_09,
  ...ELA_11,
  ...ELA_12,
  ...HSS_07,
  ...HSS_08,
  ...HSS_HGEO,
  ...HSS_MWH,
  ...HSS_US,
  ...HSS_GOV,
];
